"""SharpEdge Analytics - Advanced betting calculations."""

from sharpedge_analytics.arbitrage import (
    SPORTSBOOK_FEES,
    ArbitrageResult,
    FeeAdjustedArbitrage,
    # Fee-adjusted arbitrage
    SportsbookFees,
    calculate_arbitrage_stakes,
    find_arbitrage,
    find_arbitrage_with_fees,
    find_best_arb_combo,
    get_sportsbook_fees,
    scan_for_arbitrage,
    scan_for_arbitrage_with_fees,
)
from sharpedge_analytics.consensus import (
    BOOK_WEIGHTS,
    ConsensusResult,
    calculate_consensus_line,
    calculate_market_agreement,
    calculate_weighted_consensus,
    get_book_weight,
    line_vs_consensus,
)
from sharpedge_analytics.key_numbers import (
    KEY_NUMBERS_MLB,
    KEY_NUMBERS_NBA,
    KEY_NUMBERS_NCAAF,
    KEY_NUMBERS_NFL,
    KEY_NUMBERS_NHL,
    KeyNumberAnalysis,
    analyze_key_numbers,
    compare_lines_key_numbers,
    get_key_number_value,
    get_teaser_value,
    is_key_number,
)
from sharpedge_analytics.middles import (
    MiddleResult,
    calculate_middle_ev,
    calculate_middle_probability,
    find_middle_opportunity,
    scan_for_middles,
)
from sharpedge_analytics.movement import (
    LineMovementResult,
    MovementType,
    calculate_movement_from_open,
    classify_line_movement,
    detect_reverse_line_movement,
    detect_steam_move,
    track_movement_history,
)
from sharpedge_analytics.no_vig import (
    NoVigResult,
    calculate_edge,
    calculate_expected_value,
    calculate_fair_odds,
    calculate_no_vig_odds,
    calculate_vig_percentage,
    find_best_odds_value,
)
from sharpedge_analytics.prediction_markets import (
    PLATFORM_FEES,
    CanonicalEvent,
    MarketCorrelationNetwork,
    MarketOutcome,
    Platform,
    PlatformFees,
    PredictionMarketArbitrage,
    calculate_fee_adjusted_price,
    calculate_sizing_instructions,
    detect_probability_gap,
    find_cross_platform_arbitrage,
)
from sharpedge_analytics.public_betting import (
    PublicBettingData,
    SharpIndicator,
    SharpMoneyAnalysis,
    analyze_sharp_money,
    calculate_fade_strength,
    format_public_betting_display,
    get_consensus_lean,
    identify_sharp_plays,
)
from sharpedge_analytics.rest_travel import (
    ScheduleEdge,
    ScheduleSpot,
    TeamSchedule,
    calculate_schedule_edge,
    detect_revenge_spot,
    detect_trap_game,
    format_schedule_display,
)
from sharpedge_analytics.unified_markets import (
    CrossPlatformArbitrage,
    MarketType,
    UnifiedMarket,
    UnifiedOutcome,
    UnifiedScanner,
    calculate_hybrid_arb,
    find_cross_platform_opportunities,
)
from sharpedge_analytics.value_scanner import (
    SHARP_BOOKS,
    Confidence,
    ValuePlay,
    calculate_consensus_fair_prob,
    calculate_ev,
    classify_confidence,
    enrich_with_alpha,
    filter_value_plays,
    rank_value_plays,
    scan_for_value,
    scan_for_value_no_vig,
    summarize_value_plays,
)
from sharpedge_analytics.visualizations import (
    create_arbitrage_chart,
    create_bankroll_chart,
    create_clv_chart,
    create_ev_distribution_chart,
    create_line_movement_chart,
    create_odds_comparison_chart,
    create_public_betting_chart,
    fig_to_base64,
    fig_to_png_bytes,
)
from sharpedge_analytics.weather import (
    DOME_STADIUMS,
    VenueType,
    WeatherConditions,
    WeatherImpact,
    calculate_weather_impact,
    format_weather_display,
    get_venue_type,
    get_weather_betting_advice,
)

__all__ = [
    "BOOK_WEIGHTS",
    "DOME_STADIUMS",
    "KEY_NUMBERS_MLB",
    "KEY_NUMBERS_NBA",
    "KEY_NUMBERS_NCAAF",
    "KEY_NUMBERS_NFL",
    "KEY_NUMBERS_NHL",
    "PLATFORM_FEES",
    "SHARP_BOOKS",
    "SPORTSBOOK_FEES",
    "ArbitrageResult",
    "CanonicalEvent",
    "Confidence",
    "ConsensusResult",
    "CrossPlatformArbitrage",
    "FeeAdjustedArbitrage",
    "KeyNumberAnalysis",
    "LineMovementResult",
    "MarketCorrelationNetwork",
    "MarketOutcome",
    # Unified Markets
    "MarketType",
    "MiddleResult",
    "MovementType",
    "NoVigResult",
    # Prediction Markets
    "Platform",
    "PlatformFees",
    "PredictionMarketArbitrage",
    "PublicBettingData",
    "ScheduleEdge",
    "ScheduleSpot",
    "SharpIndicator",
    "SharpMoneyAnalysis",
    # Fee-adjusted arbitrage
    "SportsbookFees",
    "TeamSchedule",
    "UnifiedMarket",
    "UnifiedOutcome",
    "UnifiedScanner",
    "ValuePlay",
    "VenueType",
    "WeatherConditions",
    "WeatherImpact",
    "analyze_key_numbers",
    # Public Betting
    "analyze_sharp_money",
    "calculate_arbitrage_stakes",
    "calculate_consensus_fair_prob",
    # Consensus
    "calculate_consensus_line",
    "calculate_edge",
    "calculate_ev",
    "calculate_expected_value",
    "calculate_fade_strength",
    "calculate_fair_odds",
    "calculate_fee_adjusted_price",
    "calculate_hybrid_arb",
    "calculate_market_agreement",
    "calculate_middle_ev",
    "calculate_middle_probability",
    "calculate_movement_from_open",
    # No-vig
    "calculate_no_vig_odds",
    # Rest/Travel
    "calculate_schedule_edge",
    "calculate_sizing_instructions",
    "calculate_vig_percentage",
    # Weather
    "calculate_weather_impact",
    "calculate_weighted_consensus",
    "classify_confidence",
    # Movement
    "classify_line_movement",
    "compare_lines_key_numbers",
    "create_arbitrage_chart",
    "create_bankroll_chart",
    "create_clv_chart",
    "create_ev_distribution_chart",
    # Visualizations
    "create_line_movement_chart",
    "create_odds_comparison_chart",
    "create_public_betting_chart",
    "detect_probability_gap",
    "detect_revenge_spot",
    "detect_reverse_line_movement",
    "detect_steam_move",
    "detect_trap_game",
    "enrich_with_alpha",
    "fig_to_base64",
    "fig_to_png_bytes",
    "filter_value_plays",
    # Arbitrage
    "find_arbitrage",
    "find_arbitrage_with_fees",
    "find_best_arb_combo",
    "find_best_odds_value",
    "find_cross_platform_arbitrage",
    "find_cross_platform_opportunities",
    # Middles
    "find_middle_opportunity",
    "format_public_betting_display",
    "format_schedule_display",
    "format_weather_display",
    "get_book_weight",
    "get_consensus_lean",
    "get_key_number_value",
    "get_sportsbook_fees",
    "get_teaser_value",
    "get_venue_type",
    "get_weather_betting_advice",
    "identify_sharp_plays",
    # Key numbers
    "is_key_number",
    "line_vs_consensus",
    "rank_value_plays",
    "scan_for_arbitrage",
    "scan_for_arbitrage_with_fees",
    "scan_for_middles",
    # Value scanner
    "scan_for_value",
    "scan_for_value_no_vig",
    "summarize_value_plays",
    "track_movement_history",
]
