"""SharpEdge Analytics - Advanced betting calculations."""

from sharpedge_analytics.no_vig import (
    calculate_no_vig_odds,
    calculate_fair_odds,
    calculate_vig_percentage,
    calculate_edge,
    calculate_expected_value,
    find_best_odds_value,
    NoVigResult,
)
from sharpedge_analytics.consensus import (
    calculate_consensus_line,
    calculate_weighted_consensus,
    line_vs_consensus,
    calculate_market_agreement,
    get_book_weight,
    ConsensusResult,
    BOOK_WEIGHTS,
)
from sharpedge_analytics.arbitrage import (
    find_arbitrage,
    calculate_arbitrage_stakes,
    scan_for_arbitrage,
    find_best_arb_combo,
    ArbitrageResult,
    # Fee-adjusted arbitrage
    SportsbookFees,
    SPORTSBOOK_FEES,
    get_sportsbook_fees,
    FeeAdjustedArbitrage,
    find_arbitrage_with_fees,
    scan_for_arbitrage_with_fees,
)
from sharpedge_analytics.middles import (
    find_middle_opportunity,
    calculate_middle_probability,
    scan_for_middles,
    calculate_middle_ev,
    MiddleResult,
)
from sharpedge_analytics.key_numbers import (
    is_key_number,
    get_key_number_value,
    analyze_key_numbers,
    compare_lines_key_numbers,
    get_teaser_value,
    KeyNumberAnalysis,
    KEY_NUMBERS_NFL,
    KEY_NUMBERS_NCAAF,
    KEY_NUMBERS_NBA,
    KEY_NUMBERS_MLB,
    KEY_NUMBERS_NHL,
)
from sharpedge_analytics.movement import (
    classify_line_movement,
    detect_steam_move,
    detect_reverse_line_movement,
    calculate_movement_from_open,
    track_movement_history,
    LineMovementResult,
    MovementType,
)
from sharpedge_analytics.value_scanner import (
    scan_for_value,
    scan_for_value_no_vig,
    calculate_consensus_fair_prob,
    rank_value_plays,
    filter_value_plays,
    summarize_value_plays,
    calculate_ev,
    classify_confidence,
    ValuePlay,
    Confidence,
    SHARP_BOOKS,
)
from sharpedge_analytics.weather import (
    calculate_weather_impact,
    get_weather_betting_advice,
    get_venue_type,
    format_weather_display,
    WeatherConditions,
    WeatherImpact,
    VenueType,
    DOME_STADIUMS,
)
from sharpedge_analytics.rest_travel import (
    calculate_schedule_edge,
    detect_trap_game,
    detect_revenge_spot,
    format_schedule_display,
    TeamSchedule,
    ScheduleEdge,
    ScheduleSpot,
)
from sharpedge_analytics.public_betting import (
    analyze_sharp_money,
    calculate_fade_strength,
    get_consensus_lean,
    format_public_betting_display,
    identify_sharp_plays,
    PublicBettingData,
    SharpMoneyAnalysis,
    SharpIndicator,
)
from sharpedge_analytics.prediction_markets import (
    Platform,
    PlatformFees,
    PLATFORM_FEES,
    MarketOutcome,
    CanonicalEvent,
    PredictionMarketArbitrage,
    MarketCorrelationNetwork,
    find_cross_platform_arbitrage,
    detect_probability_gap,
    calculate_fee_adjusted_price,
    calculate_sizing_instructions,
)
from sharpedge_analytics.visualizations import (
    create_line_movement_chart,
    create_ev_distribution_chart,
    create_bankroll_chart,
    create_clv_chart,
    create_odds_comparison_chart,
    create_arbitrage_chart,
    create_public_betting_chart,
    fig_to_png_bytes,
    fig_to_base64,
)
from sharpedge_analytics.unified_markets import (
    MarketType,
    UnifiedOutcome,
    UnifiedMarket,
    CrossPlatformArbitrage,
    UnifiedScanner,
    find_cross_platform_opportunities,
    calculate_hybrid_arb,
)

__all__ = [
    # No-vig
    "calculate_no_vig_odds",
    "calculate_fair_odds",
    "calculate_vig_percentage",
    "calculate_edge",
    "calculate_expected_value",
    "find_best_odds_value",
    "NoVigResult",
    # Consensus
    "calculate_consensus_line",
    "calculate_weighted_consensus",
    "line_vs_consensus",
    "calculate_market_agreement",
    "get_book_weight",
    "ConsensusResult",
    "BOOK_WEIGHTS",
    # Arbitrage
    "find_arbitrage",
    "calculate_arbitrage_stakes",
    "scan_for_arbitrage",
    "find_best_arb_combo",
    "ArbitrageResult",
    # Fee-adjusted arbitrage
    "SportsbookFees",
    "SPORTSBOOK_FEES",
    "get_sportsbook_fees",
    "FeeAdjustedArbitrage",
    "find_arbitrage_with_fees",
    "scan_for_arbitrage_with_fees",
    # Middles
    "find_middle_opportunity",
    "calculate_middle_probability",
    "scan_for_middles",
    "calculate_middle_ev",
    "MiddleResult",
    # Key numbers
    "is_key_number",
    "get_key_number_value",
    "analyze_key_numbers",
    "compare_lines_key_numbers",
    "get_teaser_value",
    "KeyNumberAnalysis",
    "KEY_NUMBERS_NFL",
    "KEY_NUMBERS_NCAAF",
    "KEY_NUMBERS_NBA",
    "KEY_NUMBERS_MLB",
    "KEY_NUMBERS_NHL",
    # Movement
    "classify_line_movement",
    "detect_steam_move",
    "detect_reverse_line_movement",
    "calculate_movement_from_open",
    "track_movement_history",
    "LineMovementResult",
    "MovementType",
    # Value scanner
    "scan_for_value",
    "scan_for_value_no_vig",
    "calculate_consensus_fair_prob",
    "rank_value_plays",
    "filter_value_plays",
    "summarize_value_plays",
    "calculate_ev",
    "classify_confidence",
    "ValuePlay",
    "Confidence",
    "SHARP_BOOKS",
    # Weather
    "calculate_weather_impact",
    "get_weather_betting_advice",
    "get_venue_type",
    "format_weather_display",
    "WeatherConditions",
    "WeatherImpact",
    "VenueType",
    "DOME_STADIUMS",
    # Rest/Travel
    "calculate_schedule_edge",
    "detect_trap_game",
    "detect_revenge_spot",
    "format_schedule_display",
    "TeamSchedule",
    "ScheduleEdge",
    "ScheduleSpot",
    # Public Betting
    "analyze_sharp_money",
    "calculate_fade_strength",
    "get_consensus_lean",
    "format_public_betting_display",
    "identify_sharp_plays",
    "PublicBettingData",
    "SharpMoneyAnalysis",
    "SharpIndicator",
    # Prediction Markets
    "Platform",
    "PlatformFees",
    "PLATFORM_FEES",
    "MarketOutcome",
    "CanonicalEvent",
    "PredictionMarketArbitrage",
    "MarketCorrelationNetwork",
    "find_cross_platform_arbitrage",
    "detect_probability_gap",
    "calculate_fee_adjusted_price",
    "calculate_sizing_instructions",
    # Visualizations
    "create_line_movement_chart",
    "create_ev_distribution_chart",
    "create_bankroll_chart",
    "create_clv_chart",
    "create_odds_comparison_chart",
    "create_arbitrage_chart",
    "create_public_betting_chart",
    "fig_to_png_bytes",
    "fig_to_base64",
    # Unified Markets
    "MarketType",
    "UnifiedOutcome",
    "UnifiedMarket",
    "CrossPlatformArbitrage",
    "UnifiedScanner",
    "find_cross_platform_opportunities",
    "calculate_hybrid_arb",
]
